version: '3'
services:
  php:
    image: "kwyjibos/appstack:0.1.0"
    volumes:
     - ./workspace:/opt/app
  nginx:
    image: "nginx"
    volumes:
     - ./workspace:/opt/app
     - ./nginx-site.conf:/etc/nginx/conf.d/000_site.conf
    ports:
     - "8080:80"
  redis:
    image: "redis:4"
